sudo: required
services:
  -docker


before_install:
  - docker build -t christina0821/docker-react -f dockerfile.dev .


script:
  - docker run christina0821/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-544863999112"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"